### ISSUE TITLE
Provisioning of VM extension SetUpCEF has timed out

### ISSUE THREAD

**Issue by sukster** [hunters-forge/Blacksmith#11]
Hello,

First, thank you for creating this exciting open source project! I was deploying this template from here: https://github.com/OTRF/Azure-Sentinel2Go/tree/master/grocery-list/Win10-PAN-FW but the deployment failed with this error message: "Provisioning of VM extension SetUpCEF has timed out. Extension provisioning has taken too long to complete. The extension last reported "Plugin enabled". More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot". This was for the resource CEF-SYSLOG. Would you mind trying provisioning the same template and see if you get the same error?

Thanks, Ludek

**Comment by Cyb3rWard0g** [comment]
Hello @sukster ! thank you for the feedback. Let me test that this weekend and I will get back to you.

**Comment by sukster** [comment]
Thanks a lot Roberto!

**Comment by sukster** [comment]
Hi Roberto,

Sorry, I know you are probably busy with something else but did you have a chance to look into this?

Thanks, Ludek
