### ISSUE TITLE
CreateADPDC.zip Not found 

### ISSUE THREAD

**Issue by chihebchebbi** [hunters-forge/Blacksmith#12]
Can you please point me to the new path of "resources/scripts/powershell/active-directory/DSC/CreateADPDC.zip" since i had issue when deploying the APT29 environments? 

Thank you in advance

**Comment by Cyb3rWard0g** [comment]
https://github.com/OTRF/Blacksmith/tree/master/resources/scripts/powershell/dsc/active-directory

Slowly migrating everything from OTRF SimuLand to https://github.com/Azure/SimuLand

**Comment by Liam929** [comment]
@chihebchebbi Have you already got the new path of "resources/scripts/powershell/active-directory/DSC/CreateADPDC.zip"?

**Comment by Liam929** [comment]
@Cyb3rWard0g @shawnadrockleonard The file  "resources/scripts/powershell/active-directory/DSC/CreateADPDC.zip" cannot be found when I try to deploy the APT29 environments.I would appreciate it if you can provide me with the latest path of the requested file.
