### ISSUE TITLE
Listing endpoints to install azure monitor agent. - Blacksmith/templates/azure/Azure-Monitor-Agents/linux.json

### ISSUE THREAD

**Issue by raiwants** [hunters-forge/Blacksmith#16]
The format is specified to be an array of endpoints with a property/attribute named 'vmName'. 
Can you provide an example on what the input should look like, I have supplied an array but keep getting an error.

**Comment by Cyb3rWard0g** [comment]
Hello @raiwants ! It is an array of "Objects":

https://github.com/OTRF/Blacksmith/blob/master/templates/azure/Linux/azuredeploy.json#L350-L361

I do that to standardize some of the scripts I use with Windows and Linux VMs. Some ARM templates require the name of the extension used to run custom scripts. I hope this is helpful.
