### ISSUE TITLE
Could not find Covenant C2 web-application

### ISSUE THREAD

**Issue by Zephyrasgit** [hunters-forge/Blacksmith#3]
We have deployed the CloudFormation stacks as mentioned in the Blacksmith documentations, but could not find a way to access the Covenant C2 web-application. We think the Covenant web-application is in the RTO server, but we cannot seem to access it through browser. Can you provide us with a guide to what we do next after deployment?

**Comment by Cyb3rWard0g** [comment]
Hey @Zephyrasgit sorry for the late response. you will have to browse to :
```
https://<public covenant IP>:7443
```
Let me know if that works.
