### ISSUE TITLE
Unable to Create Windows DC Stack due to Outdated AMI

### ISSUE THREAD

**Issue by sharmaharjeet92** [hunters-forge/Blacksmith#7]
Hi Team,

While deploying the service via cloudformation template, I got the below error

> API: ec2:RunInstances Not authorized for images: [ami-02b212aba9eb84405]

<img width="1640" alt="Screenshot 2020-04-28 at 8 40 38 AM" src="https://user-images.githubusercontent.com/39051185/80443235-5bcdc600-892c-11ea-9c08-b7dc0e15385d.png">

As per [https://stackoverflow.com/questions/22653307/aws-ami-deprecation-api-ec2runinstances-not-authorized-for-images](url) comment,looks like the AMI is deprecated.

**Comment by Cyb3rWard0g** [comment]
Thank you for the heads up @sharmaharjeet92 . After a few months of changing orgs and working on other projects I decided to remove the AWS setups since it is only me managing all those other environments. I will get to it in the future.
